#!/bin/bash

red="\033[01;31m"
green="\033[01;32m"
blue="\033[01;34m"
white="\033[01;37m"
nc="\033[0m"
bold="\033[1m"

echo 
echo -e "${bold}${white}============================================================"
echo -e "         Shell tools - by Cubbins"
echo -e "============================================================"
echo 
echo -e "> MAIN MENU"
echo
echo -e "  [1] - Update sources for ROM (force update!)"
echo -e "  [2] - Update device sources from Sony repo"
echo 
echo -e -n "Enter option: "
read -n1 opt

case $opt in
    1)
        echo
        read -p "Are you sure? [Y/n]: " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            bash ./update.sh
        else
            bash ./menu
        fi
        ;;
esac